"""
Runtime configuration for nixarr-py.

Configuration is loaded from a JSON file generated by NixOS.
The path can be overridden via the NIXARR_PY_CONFIG_PATH environment variable
for testing and development.
"""

from pathlib import Path
import os
import json
from functools import cache
from pydantic import BaseModel


DEFAULT_CONFIG_PATH = "/etc/nixarr/nixarr-py.json"


class SimpleService(BaseModel):
    base_url: str
    api_key_file: Path


class NixarrPyConfig(BaseModel):
    lidarr: SimpleService | None = None
    prowlarr: SimpleService | None = None
    radarr: SimpleService | None = None
    readarr_audiobook: SimpleService | None = None
    readarr: SimpleService | None = None
    sonarr: SimpleService | None = None
    whisparr: SimpleService | None = None
    jellyfin: SimpleService | None = None


@cache
def load_config() -> NixarrPyConfig:
    """Load nixarr-py configuration from file."""
    config_path = os.environ.get("NIXARR_PY_CONFIG_PATH", DEFAULT_CONFIG_PATH)

    if not Path(config_path).is_file():
        raise FileNotFoundError(f"Config file not found: {config_path}")

    with open(config_path, "r", encoding="utf-8") as f:
        return NixarrPyConfig.model_validate(json.load(f))


def get_simple_service_config(service: str) -> SimpleService:
    """Get the SimpleService config for a given service.

    Args:
        service: The service name (e.g., "sonarr", "radarr")

    Returns:
        SimpleService: The configuration for the specified service.

    Raises:
        AssertionError: If no configuration is found for the given service, or
            if the service is not a simple service.
    """
    config = load_config()
    simple_service = getattr(config, service, None)
    assert simple_service is not None, f"No configuration found for service: {service}"
    assert isinstance(simple_service, SimpleService), (
        f"{service} is not a simple service"
    )

    return simple_service
