{
  pkgs,
  nixosModules,
}:
let
  setupScript = pkgs.writeText "setup.py" ''
    import time
    print("Waiting for Jellyfin to initialize...")
    time.sleep(5)
  '';

  verifyScript = pkgs.writeText "verify.py" ''
    import requests
    import sys
    import time

    url = "http://localhost:8096"

    # Wait for API key to be generated by the service
    for _ in range(30):
        try:
            with open("/data/.state/nixarr/api-keys/jellyfin.key") as f:
                token = f.read().strip()
            if token:
                break
        except FileNotFoundError:
            time.sleep(1)
    else:
        print("API key file not found or empty")
        sys.exit(1)

    headers = {"X-Emby-Token": token}

    # Check if wizard is completed
    try:
        resp = requests.get(url + "/Startup/Info", headers=headers)
        resp.raise_for_status()
        startup_info = resp.json()
        if not startup_info.get("Completed", False):
            print("Wizard not completed!")
            sys.exit(1)
        print("Wizard completed successfully")
    except Exception as e:
        print(f"Warning: Could not verify wizard completion: {e}")

    # Check users
    resp = requests.get(url + "/Users", headers=headers)
    resp.raise_for_status()
    users = [u["Name"] for u in resp.json()]

    if "testuser" in users:
        print("User found")
    else:
        print(f"User not found. Users: {users}")
        sys.exit(1)
  '';
in
pkgs.testers.runNixOSTest {
  name = "jellyfin-users-test";

  nodes.machine = {
    config,
    lib,
    pkgs,
    ...
  }: {
    imports = [nixosModules.default];

    networking.firewall.enable = false;

    # Jellyfin requires at least 2GB free disk space
    virtualisation.diskSize = 4096;

    environment.systemPackages = [ 
      (pkgs.python3.withPackages (ps: [ ps.requests ]))
      pkgs.sqlite
    ];

    nixarr = {
      enable = true;
      jellyfin = {
        enable = true;
        users = [
          {
            name = "admin";
            passwordFile = "/etc/jellyfin/admin-password";
          }
          {
            name = "testuser";
            passwordFile = "/etc/jellyfin/testuser-password";
          }
        ];
      };
    };

    systemd.services.jellyfin-settings-sync.wantedBy = lib.mkForce [];
  };

  testScript = ''
    import time
    machine.wait_for_unit("jellyfin.service")
    machine.succeed("systemctl stop jellyfin-settings-sync.service || true")
    machine.wait_for_open_port(8096)

    # Create password file
    machine.succeed("mkdir -p /etc/jellyfin")
    machine.succeed("echo 's3cr3t' > /etc/jellyfin/testuser-password")
    machine.succeed("echo 'admin123' > /etc/jellyfin/admin-password")

    # Wait for Jellyfin to be fully ready
    time.sleep(60)

    # Complete Wizard and get API Key
    try:
        machine.succeed("python3 ${setupScript}")
    except Exception:
        machine.succeed("journalctl -u jellyfin -n 100")
        raise

    # Now that API key exists, start the sync service
    machine.succeed("systemctl start jellyfin-api-key.service")
    machine.succeed("systemctl start jellyfin-settings-sync.service")
    
    # Verify user exists
    machine.succeed("python3 ${verifyScript}")
  '';
}
